using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Models.AutoGenerated;

public partial class Categoria
{
    [Key]
    public int Id { get; set; }

    [StringLength(400)]
    public string Descricao { get; set; } = null!;

    public int Finalidade { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Categoria")]
    public virtual ICollection<Transacao> Transacoes { get; set; } = new List<Transacao>();
}
