using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Models.AutoGenerated;

public partial class Pessoa
{
    [Key]
    public int Id { get; set; }

    [StringLength(200)]
    public string Nome { get; set; } = null!;

    public int Idade { get; set; }

    [InverseProperty("Pessoa")]
    public virtual ICollection<Transacao> Transacoes { get; set; } = new List<Transacao>();
}
