using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Models.AutoGenerated;

[Index("CategoriaId", "IsDeleted", Name = "IX_Transacoes_CategoriaId_IsDeleted")]
[Index("Data", Name = "IX_Transacoes_Data")]
[Index("PessoaId", "IsDeleted", Name = "IX_Transacoes_PessoaId_IsDeleted")]
public partial class Transacao
{
    [Key]
    public int Id { get; set; }

    [StringLength(400)]
    public string Descricao { get; set; } = null!;

    [Precision(18, 2)]
    public decimal Valor { get; set; }

    public int Tipo { get; set; }

    public int CategoriaId { get; set; }

    public int PessoaId { get; set; }

    public DateTime Data { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("CategoriaId")]
    [InverseProperty("Transacoes")]
    public virtual Categoria Categoria { get; set; } = null!;

    [ForeignKey("PessoaId")]
    [InverseProperty("Transacoes")]
    public virtual Pessoa Pessoa { get; set; } = null!;
}
