using AutoMapper;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;

namespace GastosResidenciais.Mappings;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        // Pessoa
        CreateMap<PessoaRequest, Pessoa>();
        CreateMap<PessoaUpdateRequest, Pessoa>();
        CreateMap<Pessoa, PessoaResponse>();

        // Categoria
        CreateMap<CategoriaRequest, Categoria>();
        CreateMap<CategoriaUpdateRequest, Categoria>(); // <-- adicionar
        CreateMap<Categoria, CategoriaResponse>()
            .ForMember(dest => dest.FinalidadeLabel,
                opt => opt.MapFrom(src => ObterFinalidadeLabel(src.Finalidade)));

        // Transacao
        CreateMap<TransacaoRequest, Transacao>();
        CreateMap<Transacao, TransacaoResponse>()
            .ForMember(dest => dest.TipoLabel,
                opt => opt.MapFrom(src => ObterTipoLabel(src.Tipo)))
            .ForMember(dest => dest.CategoriaDescricao,
                opt => opt.MapFrom(src => src.Categoria != null ? src.Categoria.Descricao : ""))
            .ForMember(dest => dest.PessoaNome,
                opt => opt.MapFrom(src => src.Pessoa != null ? src.Pessoa.Nome : ""));
        CreateMap<Transacao, TransacaoDto>()
            .ForMember(dest => dest.CategoriaDescricao,
                opt => opt.MapFrom(src => src.Categoria != null ? src.Categoria.Descricao : ""))
            .ForMember(dest => dest.PessoaNome,
                opt => opt.MapFrom(src => src.Pessoa != null ? src.Pessoa.Nome : ""));
    }

    private static string ObterFinalidadeLabel(int finalidade)
    {
        if (finalidade == 1) return "Despesa";
        if (finalidade == 2) return "Receita";
        if (finalidade == 3) return "Ambas";
        return "Desconhecido";
    }

    private static string ObterTipoLabel(int tipo)
    {
        if (tipo == 1) return "Despesa";
        if (tipo == 2) return "Receita";
        return "Desconhecido";
    }
}
