using AutoMapper;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services.Interfaces;

namespace GastosResidenciais.Services;

public class CategoriaService : ICategoriaService
{
    private readonly ICategoriaRepository _categoriaRepository;
    private readonly IMapper _mapper;
    private readonly IValidator<CategoriaRequest> _validator;
    private readonly IValidator<CategoriaUpdateRequest> _validatorUpdate;

    public CategoriaService(
        ICategoriaRepository categoriaRepository, 
        IMapper mapper, 
        IValidator<CategoriaRequest> validator, 
        IValidator<CategoriaUpdateRequest> validatorUpdate)
    {
        _categoriaRepository = categoriaRepository;
        _mapper = mapper;
        _validator = validator;
        _validatorUpdate = validatorUpdate;
    }

    public async Task<CategoriaResponse> CriarAsync(CategoriaRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _validator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new FluentValidation.ValidationException(validationResult.Errors);

        var existentes = await _categoriaRepository.ListarAsync(cancellationToken);
        if (existentes.Any(c => c.Descricao.Equals(request.Descricao, StringComparison.OrdinalIgnoreCase)))
            throw new ArgumentException("Já existe uma categoria cadastrada com esta descrição.");

        var categoria = _mapper.Map<Categoria>(request);
        var criada = await _categoriaRepository.CriarAsync(categoria, cancellationToken);
        return _mapper.Map<CategoriaResponse>(criada);
    }

    public async Task<IEnumerable<CategoriaResponse>> ListarAsync(CancellationToken cancellationToken = default)
    {
        var categorias = await _categoriaRepository.ListarAsync(cancellationToken);
        return _mapper.Map<IEnumerable<CategoriaResponse>>(categorias);
    }

    public async Task<CategoriaResponse?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        var categoria = await _categoriaRepository.BuscarPorIdAsync(id, cancellationToken);
        return categoria is null ? null : _mapper.Map<CategoriaResponse>(categoria);
    }

    public async Task<CategoriaResponse> AtualizarAsync(int id, CategoriaUpdateRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _validatorUpdate.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new FluentValidation.ValidationException(validationResult.Errors);

        var categoria = await _categoriaRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Categoria não encontrada.");

        var existe = await _categoriaRepository.ExisteCategoriaComDescricaoAsync(request.Descricao, id, cancellationToken);
        if (existe && !string.Equals(categoria.Descricao, request.Descricao, StringComparison.OrdinalIgnoreCase))
            throw new ArgumentException("Já existe uma categoria com essa descrição.");

        // mapear: se usar AutoMapper, garanta o CreateMap para CategoriaUpdateRequest
        _mapper.Map(request, categoria);
        var atualizada = await _categoriaRepository.AtualizarAsync(categoria, cancellationToken);
        return _mapper.Map<CategoriaResponse>(atualizada);
    }

    public async Task DeletarAsync(int id, CancellationToken cancellationToken = default)
    {
        var categoria = await _categoriaRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Categoria não encontrada.");

        await _categoriaRepository.DeletarAsync(categoria, cancellationToken);
    }
}
