using AutoMapper;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services.Interfaces;

namespace GastosResidenciais.Services;

public class PessoaService : IPessoaService
{
    private readonly IPessoaRepository _pessoaRepository;
    private readonly IMapper _mapper;
    private readonly IValidator<PessoaRequest> _createValidator;
    private readonly IValidator<PessoaUpdateRequest> _updateValidator;

    public PessoaService(
        IPessoaRepository pessoaRepository, 
        IMapper mapper, 
        IValidator<PessoaRequest> createValidator, 
        IValidator<PessoaUpdateRequest> updateValidator)
    {
        _pessoaRepository = pessoaRepository;
        _mapper = mapper;
        _createValidator = createValidator;
        _updateValidator = updateValidator;
    }

    public async Task<PessoaResponse> AtualizarAsync(int id, PessoaUpdateRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _updateValidator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new ValidationException(validationResult.Errors);

        var pessoa = await _pessoaRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Pessoa não encontrada.");

        var existentes = await _pessoaRepository.ListarAsync(cancellationToken);
        if (existentes.Any(p => p.Id != id && p.Nome.Equals(request.Nome, StringComparison.OrdinalIgnoreCase)))
            throw new ArgumentException("Já existe uma pessoa cadastrada com este nome.");

        _mapper.Map(request, pessoa);
        var atualizada = await _pessoaRepository.AtualizarAsync(pessoa, cancellationToken);
        return _mapper.Map<PessoaResponse>(atualizada);
    }

    public async Task<PessoaResponse?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        var pessoa = await _pessoaRepository.BuscarPorIdAsync(id, cancellationToken);
        return pessoa is null ? null : _mapper.Map<PessoaResponse>(pessoa);
    }

    public async Task<PessoaResponse> CriarAsync(PessoaRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _createValidator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new ValidationException(validationResult.Errors);

        var existentes = await _pessoaRepository.ListarAsync(cancellationToken);
        if (existentes.Any(p => p.Nome.Equals(request.Nome, StringComparison.OrdinalIgnoreCase)))
            throw new ArgumentException("Já existe uma pessoa cadastrada com este nome.");

        var pessoa = _mapper.Map<Pessoa>(request);
        var criada = await _pessoaRepository.CriarAsync(pessoa, cancellationToken);
        return _mapper.Map<PessoaResponse>(criada);
    }

    public async Task DeletarAsync(int id, CancellationToken cancellationToken = default)
    {
        var pessoa = await _pessoaRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Pessoa não encontrada.");

        await _pessoaRepository.DeletarAsync(pessoa, cancellationToken);
    }

    public async Task<IEnumerable<PessoaResponse>> ListarAsync(CancellationToken cancellationToken = default)
    {
        var pessoas = await _pessoaRepository.ListarAsync(cancellationToken);
        return _mapper.Map<IEnumerable<PessoaResponse>>(pessoas);
    }
}
