using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services.Interfaces;

namespace GastosResidenciais.Services;

public class RelatorioService : IRelatorioService
{
    private readonly IRelatorioRepository _relatorioRepository;

    public RelatorioService(IRelatorioRepository relatorioRepository)
    {
        _relatorioRepository = relatorioRepository;
    }

    public async Task<RelatorioResponse> TotaisPorPessoaAsync(CancellationToken cancellationToken = default)
    {
        var pessoas = await _relatorioRepository.ListarPessoasComTransacoesAsync(cancellationToken);

        var itens = pessoas
            // se Transacoes puder ser null, proteja com ?? Enumerable.Empty<Transacao>()
            .Select(p =>
            {
                var transacoesAtivas = (p.Transacoes ?? Enumerable.Empty<Transacao>())
                    .Where(t => !t.IsDeleted); // considera apenas transações não deletadas

                var receitas = transacoesAtivas.Where(t => t.Tipo == 2).Sum(t => t.Valor);
                var despesas = transacoesAtivas.Where(t => t.Tipo == 1).Sum(t => t.Valor);

                return new TotaisItem
                {
                    Id = p.Id,
                    Nome = p.Nome,
                    Receitas = receitas,
                    Despesas = despesas,
                    Saldo = receitas - despesas
                };
            })
            // remove pessoas sem movimentação (ambos zero)
            .Where(i => i.Receitas != 0m || i.Despesas != 0m)
            .ToList();

        return new RelatorioResponse
        {
            Itens = itens,
            TotalReceitas = itens.Sum(i => i.Receitas),
            TotalDespesas = itens.Sum(i => i.Despesas),
            SaldoLiquido = itens.Sum(i => i.Receitas) - itens.Sum(i => i.Despesas)
        };
    }

    public async Task<RelatorioResponse> TotaisPorCategoriaAsync(CancellationToken cancellationToken = default)
    {
        var categorias = await _relatorioRepository.ListarCategoriasComTransacoesAsync(cancellationToken);

        var itens = categorias
            // filtra categorias ativas (IsDeleted == false)
            .Where(c => !c.IsDeleted)
            .Select(c =>
            {
                var receitas = c.Transacoes
                    .Where(t => !t.IsDeleted && t.Tipo == 2)
                    .Sum(t => t.Valor);

                var despesas = c.Transacoes
                    .Where(t => !t.IsDeleted && t.Tipo == 1)
                    .Sum(t => t.Valor);

                return new TotaisItem
                {
                    Id = c.Id,
                    Nome = c.Descricao,
                    Receitas = receitas,
                    Despesas = despesas,
                    Saldo = receitas - despesas
                };
            })
            // remove categorias sem movimentação (ambos zero)
            .Where(i => i.Receitas != 0m || i.Despesas != 0m)
            .ToList();

        return new RelatorioResponse
        {
            Itens = itens,
            TotalReceitas = itens.Sum(i => i.Receitas),
            TotalDespesas = itens.Sum(i => i.Despesas),
            SaldoLiquido = itens.Sum(i => i.Receitas) - itens.Sum(i => i.Despesas)
        };
    }
}
