using AutoMapper;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services.Interfaces;

namespace GastosResidenciais.Services;

public class TransacaoService : ITransacaoService
{
    private readonly ITransacaoRepository _transacaoRepository;
    private readonly IPessoaRepository _pessoaRepository;
    private readonly ICategoriaRepository _categoriaRepository;
    private readonly IMapper _mapper;
    private readonly IValidator<TransacaoRequest> _validator;

    public TransacaoService(
        ITransacaoRepository transacaoRepository,
        IPessoaRepository pessoaRepository,
        ICategoriaRepository categoriaRepository,
        IMapper mapper,
        IValidator<TransacaoRequest> validator)
    {
        _transacaoRepository = transacaoRepository;
        _pessoaRepository = pessoaRepository;
        _categoriaRepository = categoriaRepository;
        _mapper = mapper;
        _validator = validator;
    }

    public async Task<TransacaoResponse> CriarAsync(TransacaoRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _validator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new FluentValidation.ValidationException(validationResult.Errors);

        var pessoa = await _pessoaRepository.BuscarPorIdAsync(request.PessoaId, cancellationToken)
            ?? throw new KeyNotFoundException("Pessoa não encontrada.");

        if (pessoa.Idade < 18 && request.Tipo == 2)
            throw new InvalidOperationException("Menores de 18 anos só podem registrar despesas.");

        var categoria = await _categoriaRepository.BuscarPorIdAsync(request.CategoriaId, cancellationToken)
            ?? throw new KeyNotFoundException("Categoria não encontrada.");

        var compativel = categoria.Finalidade == 3
            || (categoria.Finalidade == 1 && request.Tipo == 1)
            || (categoria.Finalidade == 2 && request.Tipo == 2);

        if (!compativel)
            throw new InvalidOperationException(
                $"A categoria '{categoria.Descricao}' não é compatível com transações do tipo '{(request.Tipo == 1 ? "Despesa" : "Receita")}'.");

        var transacao = _mapper.Map<Transacao>(request);
        var criada = await _transacaoRepository.CriarAsync(transacao, cancellationToken);

        criada.Pessoa = pessoa;
        criada.Categoria = categoria;

        return _mapper.Map<TransacaoResponse>(criada);
    }

    public async Task<IEnumerable<TransacoesPorPessoaDto>> ListarAsync(CancellationToken cancellationToken = default)
    {
        var transacoesAgrupadas = await _transacaoRepository.ListarAgrupadoPorPessoaAsync(cancellationToken);

        var result = transacoesAgrupadas.Select(g => new TransacoesPorPessoaDto
        {
            PessoaId = g.PessoaId,
            PessoaNome = g.PessoaNome,
            Transacoes = _mapper.Map<List<TransacaoDto>>(g.Transacoes)
        });

        return result;
    }

    public async Task<TransacaoResponse?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        var t = await _transacaoRepository.BuscarPorIdAsync(id, cancellationToken);
        if (t is null) return null;

        return _mapper.Map<TransacaoResponse>(t);
    }

    public async Task<TransacaoResponse> AtualizarAsync(int id, TransacaoRequest request, CancellationToken cancellationToken = default)
    {
        ValidationResult validationResult = await _validator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new FluentValidation.ValidationException(validationResult.Errors);

        var existente = await _transacaoRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Transação não encontrada.");

        var pessoa = await _pessoaRepository.BuscarPorIdAsync(request.PessoaId, cancellationToken)
            ?? throw new KeyNotFoundException("Pessoa não encontrada.");

        var categoria = await _categoriaRepository.BuscarPorIdAsync(request.CategoriaId, cancellationToken)
            ?? throw new KeyNotFoundException("Categoria não encontrada.");

        if (pessoa.Idade < 18 && request.Tipo == 2)
            throw new InvalidOperationException("Menores de 18 anos só podem registrar despesas.");

        var compativel = categoria.Finalidade == 3
            || (categoria.Finalidade == 1 && request.Tipo == 1)
            || (categoria.Finalidade == 2 && request.Tipo == 2);

        if (!compativel)
            throw new InvalidOperationException($"A categoria '{categoria.Descricao}' não é compatível com transações do tipo '{(request.Tipo == 1 ? "Despesa" : "Receita")}'.");

        _mapper.Map(request, existente);

        var atualizada = await _transacaoRepository.AtualizarAsync(existente, cancellationToken);

        atualizada.Pessoa = pessoa;
        atualizada.Categoria = categoria;

        return _mapper.Map<TransacaoResponse>(atualizada);
    }

    public async Task DeletarAsync(int id, CancellationToken cancellationToken = default)
    {
        var existente = await _transacaoRepository.BuscarPorIdAsync(id, cancellationToken)
            ?? throw new KeyNotFoundException("Transação não encontrada.");

        await _transacaoRepository.DeletarAsync(existente, cancellationToken);
    }
}
    