using GastosResidenciais.Data;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Repositories;

public class CategoriaRepository : ICategoriaRepository
{
    private readonly AppDbContext _appDbContext;

    public CategoriaRepository(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<Categoria?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Categorias
            .AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == id, cancellationToken);
    }

    public async Task<Categoria> CriarAsync(Categoria categoria, CancellationToken cancellationToken = default)
    {
        _appDbContext.Categorias.Add(categoria);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return categoria;
    }

    public async Task<IEnumerable<Categoria>> ListarAsync(CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Categorias
            .AsNoTracking()
            .Where(c => !c.IsDeleted)
            .OrderBy(c => c.Descricao)
            .ToListAsync(cancellationToken);
    }

    public async Task<Categoria> AtualizarAsync(Categoria categoria, CancellationToken cancellationToken = default)
    {
        _appDbContext.Categorias.Update(categoria);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return categoria;
    }

    public async Task DeletarAsync(Categoria categoria, CancellationToken cancellationToken = default)
    {
        if (categoria == null) return;

        categoria.IsDeleted = true;
        _appDbContext.Categorias.Update(categoria);
        await _appDbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task<bool> ExisteCategoriaComDescricaoAsync(string descricao, int? ignoreId = null, CancellationToken ct = default)
    {
        return await _appDbContext.Categorias
            .AnyAsync(c => !c.IsDeleted
                           && c.Descricao == descricao
                           && (ignoreId == null || c.Id != ignoreId), ct);
    }
}
