using GastosResidenciais.Data;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Repositories;

public class PessoaRepository : IPessoaRepository
{
    private readonly AppDbContext _appDbContext;

    public PessoaRepository(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<Pessoa> AtualizarAsync(Pessoa pessoa, CancellationToken cancellationToken = default)
    {
        _appDbContext.Pessoas.Update(pessoa);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return pessoa;
    }

    public async Task<Pessoa?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Pessoas
            .AsNoTracking()
            .FirstOrDefaultAsync(p => p.Id == id, cancellationToken);
    }

    public async Task<Pessoa> CriarAsync(Pessoa pessoa, CancellationToken cancellationToken = default)
    {
        _appDbContext.Pessoas.Add(pessoa);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return pessoa;
    }

    public async Task DeletarAsync(Pessoa pessoa, CancellationToken cancellationToken = default)
    {
        _appDbContext.Pessoas.Remove(pessoa);
        await _appDbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task<IEnumerable<Pessoa>> ListarAsync(CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Pessoas
            .AsNoTracking()
            .OrderBy(p => p.Nome)
            .ToListAsync(cancellationToken);
    }

    public async Task<bool> ExistePorNomeAsync(string nome, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(nome)) return false;
        var lower = nome.Trim().ToLower();
        return await _appDbContext.Pessoas.AnyAsync(p => p.Nome.ToLower() == lower, cancellationToken);
    }
}
