using GastosResidenciais.Data;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Repositories;

public class RelatorioRepository : IRelatorioRepository
{
    private readonly AppDbContext _appDbContext;

    public RelatorioRepository(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<IEnumerable<Categoria>> ListarCategoriasComTransacoesAsync(CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Categorias
            .AsNoTracking()
            .Where(c => !c.IsDeleted)
            .Include(c => c.Transacoes)
            .OrderBy(c => c.Descricao)
            .ToListAsync(cancellationToken);
    }

    public async Task<IEnumerable<Pessoa>> ListarPessoasComTransacoesAsync(CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Pessoas
            .AsNoTracking()
            .Include(p => p.Transacoes.Where(t => !t.IsDeleted && !t.Categoria.IsDeleted)) // só transações ativas e categorias ativas
            .OrderBy(p => p.Nome)
            .ToListAsync(cancellationToken);
    }
}
