using GastosResidenciais.Data;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Repositories;

public class TransacaoRepository : ITransacaoRepository
{
    private readonly AppDbContext _appDbContext;

    public TransacaoRepository(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<Transacao> CriarAsync(Transacao transacao, CancellationToken cancellationToken = default)
    {
        _appDbContext.Transacoes.Add(transacao);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return transacao;
    }

    public async Task<IEnumerable<Transacao>> ListarAsync(CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Transacoes
            .AsNoTracking()
            .Where(t => !t.IsDeleted)
            .Include(t => t.Categoria)
            .Include(t => t.Pessoa)
            .OrderBy(t => t.PessoaId)
            .ThenByDescending(t => t.Id)
            .ToListAsync(cancellationToken);
    }

    public async Task<Transacao?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default)
    {
        return await _appDbContext.Transacoes
            .Include(t => t.Pessoa)
            .Include(t => t.Categoria)
            .FirstOrDefaultAsync(t => t.Id == id, cancellationToken);
    }

    public async Task<Transacao> AtualizarAsync(Transacao transacao, CancellationToken cancellationToken = default)
    {
        _appDbContext.Transacoes.Update(transacao);
        await _appDbContext.SaveChangesAsync(cancellationToken);
        return transacao;
    }

    public async Task DeletarAsync(Transacao transacao, CancellationToken cancellationToken = default)
    {
        if (transacao == null) return;

        transacao.IsDeleted = true;
        _appDbContext.Transacoes.Update(transacao);
        await _appDbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task<IEnumerable<TransacoesPorPessoaDto>> ListarAgrupadoPorPessoaAsync(CancellationToken cancellationToken = default)
    {
        var query = _appDbContext.Transacoes
            .AsNoTracking()
            .Where(t => !t.IsDeleted && !t.Categoria.IsDeleted) // filtro para transações e categorias ativas
            .Select(t => new TransacaoDto
            {
                Id = t.Id,
                Descricao = t.Descricao,
                Valor = t.Valor,
                Tipo = t.Tipo,
                CategoriaId = t.CategoriaId,
                CategoriaDescricao = t.Categoria != null ? t.Categoria.Descricao : null,
                PessoaId = t.PessoaId,
                PessoaNome = t.Pessoa != null ? t.Pessoa.Nome : null
            });

        var list = await query.ToListAsync(cancellationToken);

        var grouped = list
            .GroupBy(t => new { t.PessoaId, t.PessoaNome })
            .Select(g => new TransacoesPorPessoaDto
            {
                PessoaId = g.Key.PessoaId,
                PessoaNome = g.Key.PessoaNome,
                Transacoes = g.OrderByDescending(t => t.Id).ToList()
            })
            .OrderBy(g => g.PessoaNome) // ordena os grupos por nome da pessoa
            .ToList();

        return grouped;
    }
}
