using GastosResidenciais.Models.AutoGenerated;

namespace GastosResidenciais.Repositories.Interfaces;

public interface ICategoriaRepository
{
    Task<IEnumerable<Categoria>> ListarAsync(CancellationToken cancellationToken = default);
    Task<Categoria?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default);
    Task<Categoria> CriarAsync(Categoria categoria, CancellationToken cancellationToken = default);
    Task<Categoria> AtualizarAsync(Categoria categoria, CancellationToken cancellationToken = default);
    Task DeletarAsync(Categoria categoria, CancellationToken cancellationToken = default);
    Task<bool> ExisteCategoriaComDescricaoAsync(string descricao, int? id, CancellationToken cancellationToken = default);
}
