using GastosResidenciais.Models.AutoGenerated;

namespace GastosResidenciais.Repositories.Interfaces;

public interface IPessoaRepository
{
    Task<IEnumerable<Pessoa>> ListarAsync(CancellationToken cancellationToken = default);
    Task<Pessoa?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default);
    Task<Pessoa> CriarAsync(Pessoa pessoa, CancellationToken cancellationToken = default);
    Task<Pessoa> AtualizarAsync(Pessoa pessoa, CancellationToken cancellationToken = default);
    Task DeletarAsync(Pessoa pessoa, CancellationToken cancellationToken = default);
    Task<bool> ExistePorNomeAsync(string nome, CancellationToken cancellationToken = default);
}
