using GastosResidenciais.Models.AutoGenerated;

namespace GastosResidenciais.Repositories.Interfaces;

public interface IRelatorioRepository
{
    Task<IEnumerable<Pessoa>> ListarPessoasComTransacoesAsync(CancellationToken cancellationToken = default);
    Task<IEnumerable<Categoria>> ListarCategoriasComTransacoesAsync(CancellationToken cancellationToken = default);
}
