using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;

namespace GastosResidenciais.Repositories.Interfaces;

public interface ITransacaoRepository
{
    Task<IEnumerable<Transacao>> ListarAsync(CancellationToken cancellationToken = default);
    Task<Transacao> CriarAsync(Transacao transacao, CancellationToken cancellationToken = default);
    Task<Transacao?> BuscarPorIdAsync(int id, CancellationToken cancellationToken = default);
    Task<Transacao> AtualizarAsync(Transacao transacao, CancellationToken cancellationToken = default);
    Task DeletarAsync(Transacao transacao, CancellationToken cancellationToken = default);
    Task<IEnumerable<TransacoesPorPessoaDto>> ListarAgrupadoPorPessoaAsync(CancellationToken cancellationToken = default);
}
