using System;
using System.Collections.Generic;
using GastosResidenciais.Models.AutoGenerated;
using Microsoft.EntityFrameworkCore;

namespace GastosResidenciais.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categoria> Categorias { get; set; }

    public virtual DbSet<Pessoa> Pessoas { get; set; }

    public virtual DbSet<Transacao> Transacoes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Categorias_pkey");
        });

        modelBuilder.Entity<Pessoa>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Pessoas_pkey");
        });

        modelBuilder.Entity<Transacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Transacoes_pkey");

            entity.Property(e => e.Data).HasDefaultValueSql("now()");

            entity.HasOne(d => d.Categoria).WithMany(p => p.Transacoes)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Transacoes_Categorias");

            entity.HasOne(d => d.Pessoa).WithMany(p => p.Transacoes).HasConstraintName("FK_Transacoes_Pessoas");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
