using AutoMapper;
using FluentAssertions;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services;
using Moq;

namespace GastosResidenciais.Tests.Unit;

public class CategoriaServiceTests
{
    private readonly Mock<ICategoriaRepository> _categoriaRepoMock;
    private readonly Mock<IMapper> _mapperMock;
    private readonly Mock<IValidator<CategoriaRequest>> _createValidatorMock;
    private readonly Mock<IValidator<CategoriaUpdateRequest>> _updateValidatorMock;
    private readonly CategoriaService _service;

    public CategoriaServiceTests()
    {
        _categoriaRepoMock = new Mock<ICategoriaRepository>();
        _mapperMock = new Mock<IMapper>();
        _createValidatorMock = new Mock<IValidator<CategoriaRequest>>();
        _updateValidatorMock = new Mock<IValidator<CategoriaUpdateRequest>>();

        _service = new CategoriaService(
            _categoriaRepoMock.Object,
            _mapperMock.Object,
            _createValidatorMock.Object,
            _updateValidatorMock.Object
        );
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void SetupCreateValidatorValido()
    {
        _createValidatorMock
            .Setup(v => v.ValidateAsync(It.IsAny<CategoriaRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ValidationResult());
    }

    private void SetupUpdateValidatorValido()
    {
        _updateValidatorMock
            .Setup(v => v.ValidateAsync(It.IsAny<CategoriaUpdateRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ValidationResult());
    }

    private Categoria CriarCategoria(int id, string descricao, int finalidade) =>
        new() { Id = id, Descricao = descricao, Finalidade = finalidade };

    // ── Testes: Criar ─────────────────────────────────────────────────────────

    [Fact]
    public async Task CriarAsync_QuandoDadosValidos_DeveRetornarCategoriaResponse()
    {
        // Arrange
        SetupCreateValidatorValido();

        var request = new CategoriaRequest { Descricao = "Alimentação", Finalidade = 1 };
        var categoria = CriarCategoria(1, "Alimentação", 1);
        var response = new CategoriaResponse { Id = 1, Descricao = "Alimentação", Finalidade = 1, FinalidadeLabel = "Despesa" };

        _categoriaRepoMock
            .Setup(r => r.ListarAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<Categoria>());

        _mapperMock.Setup(m => m.Map<Categoria>(request)).Returns(categoria);
        _mapperMock.Setup(m => m.Map<CategoriaResponse>(categoria)).Returns(response);

        _categoriaRepoMock
            .Setup(r => r.CriarAsync(categoria, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        // Act
        var result = await _service.CriarAsync(request);

        // Assert
        result.Should().NotBeNull();
        result.Descricao.Should().Be("Alimentação");
        result.FinalidadeLabel.Should().Be("Despesa");
    }

    [Fact]
    public async Task CriarAsync_QuandoDescricaoDuplicada_DeveLancarArgumentException()
    {
        // Arrange
        SetupCreateValidatorValido();

        var request = new CategoriaRequest { Descricao = "Alimentação", Finalidade = 1 };

        _categoriaRepoMock
            .Setup(r => r.ListarAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<Categoria> { CriarCategoria(1, "Alimentação", 1) });

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<ArgumentException>()
            .WithMessage("*descrição*");
    }

    [Fact]
    public async Task CriarAsync_QuandoFinalidadeAmbas_DevePermitir()
    {
        // Arrange
        SetupCreateValidatorValido();

        var request = new CategoriaRequest { Descricao = "Geral", Finalidade = 3 };
        var categoria = CriarCategoria(1, "Geral", 3);
        var response = new CategoriaResponse { Id = 1, Descricao = "Geral", Finalidade = 3, FinalidadeLabel = "Ambas" };

        _categoriaRepoMock
            .Setup(r => r.ListarAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<Categoria>());

        _mapperMock.Setup(m => m.Map<Categoria>(request)).Returns(categoria);
        _mapperMock.Setup(m => m.Map<CategoriaResponse>(categoria)).Returns(response);

        _categoriaRepoMock
            .Setup(r => r.CriarAsync(categoria, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        // Act
        var result = await _service.CriarAsync(request);

        // Assert
        result.Should().NotBeNull();
        result.FinalidadeLabel.Should().Be("Ambas");
    }

    // ── Testes: Buscar ────────────────────────────────────────────────────────

    [Fact]
    public async Task BuscarPorIdAsync_QuandoCategoriaExiste_DeveRetornarCategoriaResponse()
    {
        // Arrange
        var categoria = CriarCategoria(1, "Alimentação", 1);
        var response = new CategoriaResponse { Id = 1, Descricao = "Alimentação", Finalidade = 1 };

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        _mapperMock.Setup(m => m.Map<CategoriaResponse>(categoria)).Returns(response);

        // Act
        var result = await _service.BuscarPorIdAsync(1);

        // Assert
        result.Should().NotBeNull();
        result!.Id.Should().Be(1);
    }

    [Fact]
    public async Task BuscarPorIdAsync_QuandoCategoriaNaoExiste_DeveRetornarNull()
    {
        // Arrange
        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Categoria?)null);

        // Act
        var result = await _service.BuscarPorIdAsync(99);

        // Assert
        result.Should().BeNull();
    }

    // ── Testes: Deletar ───────────────────────────────────────────────────────

    [Fact]
    public async Task DeletarAsync_QuandoCategoriaExiste_DeveDeletar()
    {
        // Arrange
        var categoria = CriarCategoria(1, "Alimentação", 1);

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        _categoriaRepoMock
            .Setup(r => r.DeletarAsync(categoria, It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        // Act
        var act = async () => await _service.DeletarAsync(1);

        // Assert
        await act.Should().NotThrowAsync();
        _categoriaRepoMock.Verify(r => r.DeletarAsync(categoria, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task DeletarAsync_QuandoCategoriaNaoExiste_DeveLancarKeyNotFoundException()
    {
        // Arrange
        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Categoria?)null);

        // Act
        var act = async () => await _service.DeletarAsync(99);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Categoria*");
    }

    // ── Testes: Atualizar ─────────────────────────────────────────────────────

    [Fact]
    public async Task AtualizarAsync_QuandoCategoriaNaoExiste_DeveLancarKeyNotFoundException()
    {
        // Arrange
        SetupUpdateValidatorValido();

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Categoria?)null);

        var request = new CategoriaUpdateRequest { Id = 99, Descricao = "Teste", Finalidade = 1 };

        // Act
        var act = async () => await _service.AtualizarAsync(99, request);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Categoria*");
    }
}
