using AutoMapper;
using FluentAssertions;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services;
using Moq;

namespace GastosResidenciais.Tests.Unit;

public class PessoaServiceTests
{
    private readonly Mock<IPessoaRepository> _pessoaRepoMock;
    private readonly Mock<IMapper> _mapperMock;
    private readonly Mock<IValidator<PessoaRequest>> _createValidatorMock;
    private readonly Mock<IValidator<PessoaUpdateRequest>> _updateValidatorMock;
    private readonly PessoaService _service;

    public PessoaServiceTests()
    {
        _pessoaRepoMock = new Mock<IPessoaRepository>();
        _mapperMock = new Mock<IMapper>();
        _createValidatorMock = new Mock<IValidator<PessoaRequest>>();
        _updateValidatorMock = new Mock<IValidator<PessoaUpdateRequest>>();

        _service = new PessoaService(
            _pessoaRepoMock.Object,
            _mapperMock.Object,
            _createValidatorMock.Object,
            _updateValidatorMock.Object
        );
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void SetupCreateValidatorValido()
    {
        _createValidatorMock
            .Setup(v => v.ValidateAsync(It.IsAny<PessoaRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ValidationResult());
    }

    private void SetupUpdateValidatorValido()
    {
        _updateValidatorMock
            .Setup(v => v.ValidateAsync(It.IsAny<PessoaUpdateRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ValidationResult());
    }

    private Pessoa CriarPessoa(int id, string nome, int idade) =>
        new() { Id = id, Nome = nome, Idade = idade };

    // ── Testes: Criar ─────────────────────────────────────────────────────────

    [Fact]
    public async Task CriarAsync_QuandoDadosValidos_DeveRetornarPessoaResponse()
    {
        // Arrange
        SetupCreateValidatorValido();

        var request = new PessoaRequest { Nome = "João Silva", Idade = 25 };
        var pessoa = CriarPessoa(1, "João Silva", 25);
        var response = new PessoaResponse { Id = 1, Nome = "João Silva", Idade = 25 };

        _pessoaRepoMock
            .Setup(r => r.ListarAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<Pessoa>());

        _mapperMock.Setup(m => m.Map<Pessoa>(request)).Returns(pessoa);
        _mapperMock.Setup(m => m.Map<PessoaResponse>(pessoa)).Returns(response);

        _pessoaRepoMock
            .Setup(r => r.CriarAsync(pessoa, It.IsAny<CancellationToken>()))
            .ReturnsAsync(pessoa);

        // Act
        var result = await _service.CriarAsync(request);

        // Assert
        result.Should().NotBeNull();
        result.Nome.Should().Be("João Silva");
        result.Idade.Should().Be(25);
    }

    [Fact]
    public async Task CriarAsync_QuandoNomeDuplicado_DeveLancarArgumentException()
    {
        // Arrange
        SetupCreateValidatorValido();

        var request = new PessoaRequest { Nome = "João Silva", Idade = 25 };

        _pessoaRepoMock
            .Setup(r => r.ListarAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(new List<Pessoa> { CriarPessoa(1, "João Silva", 25) });

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<ArgumentException>()
            .WithMessage("*nome*");
    }

    // ── Testes: Buscar ────────────────────────────────────────────────────────

    [Fact]
    public async Task BuscarPorIdAsync_QuandoPessoaExiste_DeveRetornarPessoaResponse()
    {
        // Arrange
        var pessoa = CriarPessoa(1, "João Silva", 25);
        var response = new PessoaResponse { Id = 1, Nome = "João Silva", Idade = 25 };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(pessoa);

        _mapperMock.Setup(m => m.Map<PessoaResponse>(pessoa)).Returns(response);

        // Act
        var result = await _service.BuscarPorIdAsync(1);

        // Assert
        result.Should().NotBeNull();
        result!.Id.Should().Be(1);
    }

    [Fact]
    public async Task BuscarPorIdAsync_QuandoPessoaNaoExiste_DeveRetornarNull()
    {
        // Arrange
        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Pessoa?)null);

        // Act
        var result = await _service.BuscarPorIdAsync(99);

        // Assert
        result.Should().BeNull();
    }

    // ── Testes: Deletar ───────────────────────────────────────────────────────

    [Fact]
    public async Task DeletarAsync_QuandoPessoaExiste_DeveDeletar()
    {
        // Arrange
        var pessoa = CriarPessoa(1, "João Silva", 25);

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(pessoa);

        _pessoaRepoMock
            .Setup(r => r.DeletarAsync(pessoa, It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        // Act
        var act = async () => await _service.DeletarAsync(1);

        // Assert
        await act.Should().NotThrowAsync();
        _pessoaRepoMock.Verify(r => r.DeletarAsync(pessoa, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task DeletarAsync_QuandoPessoaNaoExiste_DeveLancarKeyNotFoundException()
    {
        // Arrange
        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Pessoa?)null);

        // Act
        var act = async () => await _service.DeletarAsync(99);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Pessoa*");
    }

    // ── Testes: Atualizar ─────────────────────────────────────────────────────

    [Fact]
    public async Task AtualizarAsync_QuandoPessoaNaoExiste_DeveLancarKeyNotFoundException()
    {
        // Arrange
        SetupUpdateValidatorValido();

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Pessoa?)null);

        var request = new PessoaUpdateRequest { Id = 99, Nome = "Teste", Idade = 25 };

        // Act
        var act = async () => await _service.AtualizarAsync(99, request);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Pessoa*");
    }
}
