using AutoMapper;
using FluentAssertions;
using FluentValidation;
using FluentValidation.Results;
using GastosResidenciais.DTOs;
using GastosResidenciais.Models.AutoGenerated;
using GastosResidenciais.Repositories.Interfaces;
using GastosResidenciais.Services;
using Moq;

namespace GastosResidenciais.Tests.Unit;

public class TransacaoServiceTests
{
    private readonly Mock<ITransacaoRepository> _transacaoRepoMock;
    private readonly Mock<IPessoaRepository> _pessoaRepoMock;
    private readonly Mock<ICategoriaRepository> _categoriaRepoMock;
    private readonly Mock<IMapper> _mapperMock;
    private readonly Mock<IValidator<TransacaoRequest>> _validatorMock;
    private readonly TransacaoService _service;

    public TransacaoServiceTests()
    {
        _transacaoRepoMock = new Mock<ITransacaoRepository>();
        _pessoaRepoMock = new Mock<IPessoaRepository>();
        _categoriaRepoMock = new Mock<ICategoriaRepository>();
        _mapperMock = new Mock<IMapper>();
        _validatorMock = new Mock<IValidator<TransacaoRequest>>();

        _service = new TransacaoService(
            _transacaoRepoMock.Object,
            _pessoaRepoMock.Object,
            _categoriaRepoMock.Object,
            _mapperMock.Object,
            _validatorMock.Object
        );
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// <summary>Configura o validator para sempre retornar válido.</summary>
    private void SetupValidatorValido()
    {
        _validatorMock
            .Setup(v => v.ValidateAsync(It.IsAny<TransacaoRequest>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new ValidationResult());
    }

    private Pessoa CriarPessoa(int id, int idade) =>
        new() { Id = id, Nome = "Teste", Idade = idade };

    private Categoria CriarCategoria(int id, int finalidade) =>
        new() { Id = id, Descricao = "Categoria Teste", Finalidade = finalidade };

    [Fact]
    public async Task CriarAsync_QuandoMenorDeIdadeTentaReceita_DeveLancarInvalidOperationException()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest
        {
            Descricao = "Mesada",
            Valor = 100,
            Tipo = 2, // Receita
            PessoaId = 1,
            CategoriaId = 1
        };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(CriarPessoa(1, 16)); // menor de 18

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*18*");
    }

    [Fact]
    public async Task CriarAsync_QuandoMenorDeIdadeCriaDespesa_DevePermitir()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest
        {
            Descricao = "Lanche",
            Valor = 20,
            Tipo = 1, // Despesa
            PessoaId = 1,
            CategoriaId = 1
        };

        var pessoa = CriarPessoa(1, 16);
        var categoria = CriarCategoria(1, 1); // Despesa
        var transacao = new Transacao { Id = 1, Descricao = "Lanche", Valor = 20, Tipo = 1 };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(pessoa);

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        _mapperMock.Setup(m => m.Map<Transacao>(request)).Returns(transacao);
        _mapperMock.Setup(m => m.Map<TransacaoResponse>(transacao)).Returns(new TransacaoResponse());

        _transacaoRepoMock
            .Setup(r => r.CriarAsync(transacao, It.IsAny<CancellationToken>()))
            .ReturnsAsync(transacao);

        // Act
        var result = await _service.CriarAsync(request);

        // Assert
        result.Should().NotBeNull();
    }

    // ── Testes: Compatibilidade Categoria × Tipo ──────────────────────────────

    [Fact]
    public async Task CriarAsync_QuandoCategoriaReceita_ETipoDespesa_DeveLancarInvalidOperationException()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest
        {
            Descricao = "Teste",
            Valor = 100,
            Tipo = 1, // Despesa
            PessoaId = 1,
            CategoriaId = 1
        };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(CriarPessoa(1, 25));

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(CriarCategoria(1, 2)); // finalidade Receita

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<InvalidOperationException>()
            .WithMessage("*compatível*");
    }

    [Fact]
    public async Task CriarAsync_QuandoCategoriaAmbas_ETipoDespesa_DevePermitir()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest
        {
            Descricao = "Teste",
            Valor = 100,
            Tipo = 1, // Despesa
            PessoaId = 1,
            CategoriaId = 1
        };

        var pessoa = CriarPessoa(1, 25);
        var categoria = CriarCategoria(1, 3); // Ambas
        var transacao = new Transacao { Id = 1 };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(pessoa);

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(categoria);

        _mapperMock.Setup(m => m.Map<Transacao>(request)).Returns(transacao);
        _mapperMock.Setup(m => m.Map<TransacaoResponse>(transacao)).Returns(new TransacaoResponse());

        _transacaoRepoMock
            .Setup(r => r.CriarAsync(transacao, It.IsAny<CancellationToken>()))
            .ReturnsAsync(transacao);

        // Act
        var result = await _service.CriarAsync(request);

        // Assert
        result.Should().NotBeNull();
    }

    // ── Testes: Entidade não encontrada ───────────────────────────────────────

    [Fact]
    public async Task CriarAsync_QuandoPessoaNaoEncontrada_DeveLancarKeyNotFoundException()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest { PessoaId = 99, CategoriaId = 1, Tipo = 1, Valor = 100, Descricao = "Teste" };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Pessoa?)null);

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Pessoa*");
    }

    [Fact]
    public async Task CriarAsync_QuandoCategoriaNaoEncontrada_DeveLancarKeyNotFoundException()
    {
        // Arrange
        SetupValidatorValido();

        var request = new TransacaoRequest { PessoaId = 1, CategoriaId = 99, Tipo = 1, Valor = 100, Descricao = "Teste" };

        _pessoaRepoMock
            .Setup(r => r.BuscarPorIdAsync(1, It.IsAny<CancellationToken>()))
            .ReturnsAsync(CriarPessoa(1, 25));

        _categoriaRepoMock
            .Setup(r => r.BuscarPorIdAsync(99, It.IsAny<CancellationToken>()))
            .ReturnsAsync((Categoria?)null);

        // Act
        var act = async () => await _service.CriarAsync(request);

        // Assert
        await act.Should().ThrowAsync<KeyNotFoundException>()
            .WithMessage("*Categoria*");
    }
}
